### ISSUE TITLE
misw.jp にアクセスできない

### ISSUE THREAD

**Issue by tosuke** [MISW/misw-jp#130]
## Expected

misw.jp にアクセスでき，内容が表示される

## Actual

522 エラーによりアクセスできない

## When

不明 ~ 2023-12-03T20:43+09:00

**Comment by tosuke** [comment]
というかここ public なのかと思ったが特に問題はなさそう，書き進める

**Comment by tosuke** [comment]
www.misw.jp はなぜか登録できたので内部状態が壊れている?(昔存在した misw.jp に対する custom domain の設定がマイグレーションに失敗して機能していないし表示もされていないが重複チェックでは生きているとか)

**Comment by tsuzu** [comment]
redirect壊れていそう?

https://misw.jp → https://misw.jp/www.misw.jp
にredirectされていそう

**Comment by tsuzu** [comment]
```
tsuzu@Tsuzus-MacBook-Pro ~ % curl -i https://misw.jp
HTTP/2 302 
date: Sun, 03 Dec 2023 12:28:46 GMT
location: https://www.misw.jp
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=r380sxxqEGrkNDTIoT3mN60bgBlClxJzDO6HIlz0dCEK5yk2hkG4BODQJo4%2Fi5VmqVHt0pJ4y32B8attMpEcmIQ8kYov82U59hNxNB6yODz6Fj7f2YL05OR8Snud%2BM5jmvXme9cb"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
strict-transport-security: max-age=31536000; includeSubDomains; preload
expect-ct: max-age=86400, enforce
referrer-policy: same-origin
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
server: cloudflare
cf-ray: 82fbcfb88f2ae055-NRT
alt-svc: h3=":443"; ma=86400
```

コメントしてる間に直されてた
Thank you!

**Comment by Nanamiiiii** [comment]
Worksはtumblrの埋め込みみたいですけど，閲覧にログイン必須なんで弾かれてますね

**Comment by SUAN4423** [comment]
そうだったっけ
2023年10月に落ちる直前まではページが存在していたし、tumblrじゃない感じがするのだが、という
https://web.archive.org/web/20230601232824/https://misw.jp/works

**Comment by Nanamiiiii** [comment]
多分前に壊れて直したときに変えた？のかな
なんにせよ外部の埋め込みになるからうちのブラウザだとセキュリティでも弾かれる

**Comment by tsuzu** [comment]
Works、いつの間にかTumblrベースのものに置き換わっていたのか...えらすぎる👏
https://github.com/MISW/works-misw-jp

これをwwwだと正常に参照できていないなどがありそう？
Cloudflareの権限はすでに持っていないので憶測でものを言っています

**Comment by SnakeSneakS** [comment]
(今が実際どんな状況なのかはわかりませんが、)こんな感じのことがありましたっていうの置いておきます↓

[コード1](https://github.com/MISW/misw-jp/blob/main/src/works.ejs), [コード2](https://github.com/MISW/misw-jp/blob/main/config.yaml#L13), [修正が上手くいかなかったぽいcommit](https://github.com/MISW/misw-jp/commit/a31819b895bcad72eaa667d811b9ee4e6d581624)

2023/08/26のヘビのdiscordへのメッセージ: ![99CE9D3F-E7D1-42AE-B036-C90970DE9AE7](https://github.com/MISW/misw-jp/assets/67229777/09ba6281-e829-457a-b16f-ec16e0eb6fdf)
2023/09/30のたまかけくんがdiscordに上げていた画像(CORS): 
![F954F588-1B62-42A0-A369-3782237F4E48](https://github.com/MISW/misw-jp/assets/67229777/913c9644-3abe-4e9e-8724-f7ea00a17a65)

**Comment by CaffeeLake** [comment]
API経由だと表示されていないドメインも削除できました。

```shell
curl --request DELETE --header "Content-Type: application/json" --header "X-Auth-Email: ${EMAIL}" --header "X-Auth-Key: ${KEY}" --url "https://api.cloudflare.com/client/v4/accounts/${ID}/pages/projects/misw-jp/domains/misw.jp"
curl --request DELETE --header "Content-Type: application/json" --header "X-Auth-Email: ${EMAIL}" --header "X-Auth-Key: ${KEY}" --url "https://api.cloudflare.com/client/v4/accounts/${ID}/pages/projects/event-misw-jp/domains/event.misw.jp"
```

```json
{
  "result": null,
  "success": true,
  "errors": [],
  "messages": []
}
```

**Comment by tosuke** [comment]
`www.misw.jp`に一時的にリダイクトするようにしたのでこっちも一定期間は生かしておいたほうがいい気もするな……

**Comment by CaffeeLake** [comment]
`www.misw.jp`→`misw.jp`にリダイレクト設定しときました。

**Comment by tosuke** [comment]
よさそう、解決ということで
