### ISSUE TITLE
作品紹介ページの埋め込みが表示されない。

### ISSUE THREAD

**Issue by CaffeeLake** [MISW/misw-jp#153]
Tumblrのドメイン接続が有料になり、そのままの状態で放置されているため、作品紹介ページの埋め込みに問題が発生している。

https://help.tumblr.com/hc/ja/articles/18703144391063-%E3%83%89%E3%83%A1%E3%82%A4%E3%83%B3%E3%81%AE%E6%8E%A5%E7%B6%9A
https://github.com/MISW/misw-jp/issues/130
https://github.com/MISW/misw-jp/commit/a31819b895bcad72eaa667d811b9ee4e6d581624

![image](https://github.com/MISW/misw-jp/assets/93961902/d990ca41-9453-4d71-b5a5-bbd8f8f1fb32)
![image](https://github.com/MISW/misw-jp/assets/93961902/804812e9-902f-4eb9-a0e3-01ff2a4485f4)

**Comment by CaffeeLake** [comment]
Fixed.

**Comment by idunafu** [comment]
また表示されなくなっている。
![Image](https://github.com/user-attachments/assets/5b9a4a31-6d12-4065-ab41-4ed8ec8dd2de)
