### ISSUE TITLE
出典元不明

### ISSUE THREAD

**Issue by CaffeeLake** [MISW/misw-jp#42]
https://github.com/MISW/misw-jp/blob/d9fdc1f17e4496177abdd5c79cf2f0e110331d66/src/index.ejs#L39

**Comment by CaffeeLake** [comment]
どこの調査で最大なのかを記載する必要があり。

**Comment by LeonardoLopesHonda** [comment]
Hello, sorry but the problem was not clear to me, is it to indicate which of the 3 groups has more members?
